# Generated by Django 4.2.1 on 2023-05-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_feature', models.CharField(help_text='Feature name', max_length=30)),
                ('first_score', models.IntegerField(help_text='Feature score')),
                ('second_feature', models.CharField(help_text='Feature name', max_length=30)),
                ('second_score', models.IntegerField(help_text='Feature score')),
                ('third_feature', models.CharField(help_text='Feature name', max_length=30)),
                ('third_score', models.IntegerField(help_text='Feature score')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Account name', max_length=30)),
                ('usertype', models.CharField(help_text='Account analyze type', max_length=10)),
                ('analyze_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='analyze.analyze')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(help_text='Image url')),
                ('analyze_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.analyze')),
            ],
        ),
    ]
